apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{- .Values.airflow.prefix -}}flower"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      restartPolicy: Always
      containers:
        - name: "{{- .Values.airflow.prefix -}}flower"
          image: {{ .Values.airflow.image }}:{{ .Values.airflow.imageTag }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          env:
            - name: FLOWER_PORT
              value: "5555"
            - name: REDIS_HOST
              value: {{ template "airflow.redis.fullname" . }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.redisPassword }}
          ports:
            - name: "{{- .Values.airflow.prefix -}}flower"
              containerPort: 5555
          args: ["flower"]
