apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{- .Values.airflow.prefix -}}scheduler"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      restartPolicy: Always
      containers:
        - name: "{{- .Values.airflow.prefix -}}scheduler"
          image: {{ .Values.airflow.image }}:{{ .Values.airflow.imageTag }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          envFrom:
            - configMapRef:
                name: "{{- .Values.airflow.prefix -}}airflow-env"
          {{- if .Values.airflow.airflow_cfg.enable }}
          volumeMounts:
            - mountPath: /usr/local/airflow-cm/
              name: "{{- .Values.airflow.prefix -}}airflow-cfg"
          command: ["bash", "/usr/local/airflow-cm/bootstrap.sh"]
          {{- end }}
          args: ["scheduler", "-n", "{{ .Values.airflow.scheduler_num_runs }}", "-p"]
      volumes:
        - name: dags-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "airflow.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
        {{- if .Values.airflow.airflow_cfg.enable }}
        - name: "{{ .Values.airflow.prefix -}}airflow-cfg"
          configMap:
            name: "{{ .Values.airflow.prefix -}}airflow.cfg"
        {{ end -}}
