apiVersion: v1
kind: Service
metadata:
  name: "{{- .Values.airflow.prefix -}}web"
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - name: "{{- .Values.airflow.prefix -}}web"
      protocol: TCP
      port: 8080
      name: "{{- .Values.airflow.prefix -}}pweb"
      targetPort: "{{- .Values.airflow.prefix -}}web"
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: "{{- .Values.airflow.prefix -}}flower"
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: "{{- .Values.airflow.prefix -}}flower"
      protocol: TCP
      port: 5555
      name: "{{- .Values.airflow.prefix -}}pflower"
      targetPort: "{{- .Values.airflow.prefix -}}flower"
      nodePort: 32081
---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: "{{- .Values.airflow.prefix -}}workers"
spec:
  ports:
    - name: "{{- .Values.airflow.prefix -}}wlog"
      port: 8793
  clusterIP: None
  selector:
    app: airflow
