apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "airflow.name" . }}-web
    release: {{ .Release.Name }}
  ports:
    - name: "{{- .Values.airflow.prefix -}}web"
      protocol: TCP
      port: 8080
      name: "{{- .Values.airflow.prefix -}}pweb"
      targetPort: "{{- .Values.airflow.prefix -}}web"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-flower
  labels:
    app: {{ template "airflow.name" . }}-flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "airflow.name" . }}-flower
    release: {{ .Release.Name }}
  ports:
    - name: "{{- .Values.airflow.prefix -}}flower"
      protocol: TCP
      port: 5555
      name: "{{- .Values.airflow.prefix -}}pflower"
      targetPort: "{{- .Values.airflow.prefix -}}flower"
---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-worker
  labels:
    app: {{ template "airflow.name" . }}-worker
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: "{{- .Values.airflow.prefix -}}wlog"
      port: 8793
  clusterIP: None
  selector:
    app: {{ template "airflow.name" . }}-worker
